CREATE CONSTRAINT equipment_id IF NOT EXISTS
FOR (n:Equipment) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT document_id IF NOT EXISTS
FOR (n:Document) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT section_id IF NOT EXISTS
FOR (n:Section) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT chunk_id IF NOT EXISTS
FOR (n:Chunk) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT fault_id IF NOT EXISTS
FOR (n:Fault) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT alarm_id IF NOT EXISTS
FOR (n:Alarm) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT action_id IF NOT EXISTS
FOR (n:Action) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT parameter_id IF NOT EXISTS
FOR (n:Parameter) REQUIRE n.id IS UNIQUE;
